#tomcat
server.port: 8080

jwt:
  prefix: Bearer
  header: Authorization
  expiration: 86400000
  refreshExpiration: 604800000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:projeto
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
